{% set name = "flask-restalchemy" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6648ae2590c7c1f1bdffa1a7acd263ab2fbc96b8143307e3d810aae01696bf0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.6
    - flask-sqlalchemy >=2.3.0
    - sqlalchemy-utils >=0.30
    - flask >=1.0.0
    - sqlalchemy >=1.3,<2
    - serialchemy >=0.3.0

test:
  imports:
    - flask_restalchemy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ESSS/flask-restalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Flask extension to build REST APIs based on SQLAlchemy models
  description: |
    A Flask extension to build REST APIs. It dismiss the need of building Schema classes, 
    since usually all the information needed to serialize an SQLAlchemy instance is in the model itself.

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
    - edetec
