{% set name = "flask-restalchemy" %}
{% set version = "0.10.0" %}
{% set sha256 = "9218443aa93b4db4059980621665587c71a171c3d978e34c052c896f07febfbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ESSS/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - sqlalchemy >=1.1
    - flask-restful >=0.3
    - flask-sqlalchemy >=2.3.0

test:
  imports:
    - flask_restalchemy

about:
  home: https://github.com/ESSS/flask-restalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Flask extension to build REST APIs based on SQLAlchemy models'
  description: |
    A Flask extension to build REST APIs. It dismiss the need of building Schema classes, 
    since usually all the information needed to serialize an SQLAlchemy instance is in the model itself.

extra:
  recipe-maintainers:
    - igortg
    - lvoliveira
    - edetec
