travis:
  secure:
    BINSTAR_TOKEN: HAk5IQVlM6b7R9ugEpJbYb82hUsO4XUK/iBliPogs2LMPEtxS4cHskS8IEwAWZ0/0SRvzk8MNOmscPaMFb2O9lyTCBiXtbMrqmqOiL9z1JCyM+nWbSWDieRAYdzeiXJntlDs9Dq71x5HHCwkP4YvO32rOwppOsBHsZSlJghxtfiKJj9UyQiNNAJMm4NiN3mFxtKe6hkSHP5fm1iZY3amgTE+XAcWnYNqIn5m4l7GoucDSl2TfdURk15BdhuxYLF/dzc30YT2rDt4SYyVmgbwYRnLe5L74j/vcB2e7gDryKDtmw2ZnHcC5p4HvOG23mew19HMxC3JhqRLRkZIjZprRqwXlH1Eu5JF+FJ1gIDdd298Io/Oy2x0iMG+IQDvFMB6IqTSDxzef6x2bJLfkcNKWQnAvnhv/m5qCMQHvIpMERpmDoiMuCU/uh8Eq7vnavooc22yeLRWOBMuNbOPpWc7PXpQlpokkqZaT1zTJBSSiCI++LlU0yn3yau6mMLq7q0LEX9k2x6umjjKRDH89WcQ6LoRsvS1nIF9BvwTVE70jad3FKRHrooDf15FPdzafAoH9Xag/mFc7qd13fHDPNjnU0Mkq/+efaJPrmyy/uaz65/Jjaek1QmnDbGr4Ji7grbdPjvI+L+AsWC0PDfF0n+2M0iQsR/mZxykUpJceXN7+1U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
